### ISSUE TITLE
your new script doesnt work. cannot stst

### ISSUE THREAD

**Issue by klark231** [Pipetto-crypto/Chroot-Docs#14]
![Uploading Screenshot_2023-01-28-23-27-21-550_com.termux.jpg…]()

**Comment by klark231** [comment]
33, 185.199.109.133, 185.199.110.133, ...
Connecting to objects.githubusercontent.com|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17932601 (17M) [application/vnd.android.package-archive]
Saving to: ‘linuxdeploy-2.6.0-259.apk’

linuxdeploy-2 100%  17.10M  31.8MB/s    in 0.5s

2023-01-28 23:27:13 (31.8 MB/s) - ‘linuxdeploy-2.6.0-259.apk’ saved [17932601/17932601]

Success

Copying config
mv: cannot stat 'linux.conf': No such file or directory

Installing Termux-X11
cp: cannot stat 'termux-x11/termux-x11.zip': No such file or directory
unzip:  cannot find or open termux-x11.zip, termux-x11.zip.zip or termux-x11.zip.ZIP.
dpkg: error: cannot access archive 'termux-x11.deb': No such file or directory
Error: Unable to open file: app-debug.apk
Consider using a file under /data/local/tmp/
Error: Can't open file: app-debug.apk

Exception occurred while executing 'install':
java.lang.IllegalArgumentException: Error: Can't open file: app-debug.apk
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(Unknown Source:288)
        at com.android.server.pm.PackageManagerShellCommand.doRunInstall(Unknown Source:121)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(Unknown Source:6)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(Unknown Source:1239)
        at com.android.modules.utils.BasicShellCommandHandler.exec(Unknown Source:27)
        at android.os.ShellCommand.exec(Unknown Source:4)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onShellCommand(Unknown Source:24)
        at android.os.Binder.shellCommand(Unknown Source:0)                                                             at android.os.Binder.onTransact(Unknown Source:148)                                                             at android.content.pm.IPackageManager$Stub.onTransact(Unknown Source:28)
        at com.android.server.pm.PackageManagerService$IPackageManagerImpl.onTransact(Unknown Source:0)
        at android.os.Binder.execTransactInternal(Unknown Source:105)                                                   at android.os.Binder.execTransact(Unknown Source:16)

Starting installation
:: Installing bootstrap/rootfs ...
Checking installation path ... done
Making new disk image (512 MB) ... fail

 Mounting container
Checking file system ... done
Mounting the container:
/ ... fail

 Copying installation scripts and required files to the chroot
cp: cannot stat 'setup/*.sh': No such file or directory
chmod: cannot access '/data/local/mnt/home/android/scripts/*': No such file or directory

 Installing required dependencies                       Checking file system ... done
Mounting the container:
/ ... fail                                              Checking file system ... done
Mounting the container:                                 / ... fail
                                                         Appending important env variables to profile and setting bash as the main shell                                Checking file system ... done
Mounting the container:                                 / ... fail
                                                         Installing vnc and icewm
Checking file system ... done                           Mounting the container:
/ ... fail                                              
 Installing box64 and box86                             Checking file system ... done
Mounting the container:                                 / ... fail
                                                         First setup completed, stopping the chroot
The container is not mounted.                           
 Copying the linux-deploy wrapper script                cp: cannot stat 'linux-deploy': No such file or directory                                                       chmod: cannot access '/data/data/com.termux/files/usr/bin/linux-deploy': No such file or directory

**Comment by Pipetto-crypto** [comment]
pkg install git and retry

**Comment by klark231** [comment]
> pkg install git and retry

ok now work but how to re-run the script without reinstallimg the files. i mean how to run the container again

**Comment by Pipetto-crypto** [comment]
> ok now work but how to re-run the script without reinstallimg the files. i mean how to run the container again

You mean after the setup.sh script finished installing everything?

"linux-deploy start" to start the chroot with ssh
"linux-deploy start -w" to start the chroot with the termux-x11 server

**Comment by klark231** [comment]
> > ok now work but how to re-run the script without reinstallimg the files. i mean how to run the container again
> 
> You mean after the setup.sh script finished installing everything?
> 
> "linux-deploy start" to start the chroot with ssh "linux-deploy start -w" to start the chroot with the termux-x11 server

![Screenshot_2023-01-30-17-08-03-400_com termux](https://user-images.githubusercontent.com/11367357/215434328-4b72ea10-2c18-44d0-87e5-de3e41936265.jpg)

getting this error though. tried to restart and also tried reinstalling ssh but same problem


First do "linux-deploy stop," then can you post a screenshot of the whole command line after the "linux-deploy start" command?

EDIT: After the "linux-deploy stop" command, check if in /data/local/mnt there is a folder called home. That should contain another folder with the same name of your username. If inside the folder with your username there is only the folder "scripts" or it is empty, you can safely delete the home folder (sudo rm -rf /data/local/mnt/home)

**Comment by klark231** [comment]
~ $ linux-deploy start -w
Chroot already mounted, connecting
ssh: connect to host localhost port 22: Connection refused
~ $ sudo rm -rf /data/local/mnt/home
~ $ linux-deploy start -w

Initializing audio server before startup

Starting the chroot
Checking file system ... done
Mounting the container:
/ ... done
/proc ... done
/sys ... done
/dev ... done
/dev/shm ... done
/dev/pts ... done
/dev/tty ... done
:: Configuring core/mnt ...
:: Configuring core/net ...
:: Starting extra/ssh ... done

Binding internal storage

Binding external storage

Usage: bindfs [options] dir mountpoint
Information:
  -h      --help            Print this and exit.
  -V      --version         Print version number and exit.
          --fuse-version    Print version of FUSE library.

File ownership:
  -u      --force-user=...  Set file owner.
  -g      --force-group=... Set file group.
  -m      --mirror=...      Comma-separated list of users who will see
                            themselves as the owners of all files.
  -M      --mirror-only=... Like --mirror but disallow access for
                            all other users.
 --map=user1/user2:...      Let user2 see files of user1 as his own.
 --map-passwd=...           Load uid mapping from passwd-like file.
 --map-group=...            Load gid mapping from group-like file.
 --map-passwd-rev=...       Load reversed uid mapping from  passwd-like file.
 --map-group-rev=...        Load reversed gid mapping from group-like file.
 --uid-offset=...           Set file uid = uid + offset.
 --gid-offset=...           Set file gid = gid + offset.

Permission bits:
  -p      --perms=...       Specify permissions, similar to chmod
                            e.g. og-x,og+rD,u=rwX,g+rw  or  0644,a+X

File creation policy:
  --create-as-user          New files owned by creator (default for root). *
  --create-as-mounter       New files owned by fs mounter (default for users).
  --create-for-user=...     New files owned by specified user. *
  --create-for-group=...    New files owned by specified group. *
  --create-with-perms=...   Alter permissions of new files.

Chown policy:
  --chown-normal            Try to chown the original files (the default).
  --chown-ignore            Have all chowns fail silently.
  --chown-deny              Have all chowns fail with 'permission denied'.

Chgrp policy:
  --chgrp-normal            Try to chgrp the original files (the default).
  --chgrp-ignore            Have all chgrps fail silently.
  --chgrp-deny              Have all chgrps fail with 'permission denied'.

Chmod policy:
  --chmod-normal            Try to chmod the original files (the default).
  --chmod-ignore            Have all chmods fail silently.
  --chmod-deny              Have all chmods fail with 'permission denied'.
  --chmod-filter=...        Change permissions of chmod requests.
  --chmod-allow-x           Allow changing file execute bits in any case.

Extended attribute policy:
  --xattr-none              Do not implement xattr operations.
  --xattr-ro                Read-only xattr operations.
  --xattr-rw                Read-write xattr operations (the default).

Other file operations:
  --delete-deny             Disallow deleting files.
  --rename-deny             Disallow renaming files (within the mount).

Rate limits:
  --read-rate=...           Limit to bytes/sec that can be read.
  --write-rate=...          Limit to bytes/sec that can be written.

Miscellaneous:
  --no-allow-other          Do not add -o allow_other to fuse options.
  --realistic-permissions   Hide permission bits for actions mounter can't do.
  --ctime-from-mtime        Read file properties' change time
                            from file content modification time.
  --enable-lock-forwarding  Forward locks to the underlying FS.
  --enable-ioctl            Forward ioctl() calls (as the mounter).
  --hide-hard-links         Always report a hard link count of 1.
  --resolve-symlinks        Resolve symbolic links.
  --resolved-symlink-deletion=...  Decide how to delete resolved symlinks.
  --block-devices-as-files  Show block devices as regular files.
  --multithreaded           Enable multithreaded mode. See man page
                            for security issue with current implementation.
  --forward-odirect=...     Forward O_DIRECT (it's cleared by default).

FUSE options:
  -o opt[,opt,...]          Mount options.
  -r      -o ro             Mount strictly read-only.
  -d      -o debug          Enable debug output (implies -f).
  -f                        Foreground operation.

(*: root only)

Binfmt support not detected, skipping loading of binfmt entries
Creating the socket
:: Configuring core/mnt ...
:: Configuring core/net ...
Debian GNU/Linux 11 (bullseye) [running via Linux Deploy]
Starting: Intent { cmp=com.termux.x11/.MainActivity }
Loading shared library: /data/data/com.termux/files/usr/libexec/termux-x11/starter.apk!/lib/arm64-v8a/libx11-starter.so
Looks like com.termux lacks "Draw Over Apps" permission.
You can grant com.termux the "Draw Over Apps" permission from its App Info activity:
        Android Settings -> Apps -> Termux -> Advanced -> Draw over other apps.
res = 0
Activity is started
Android reported activity started but we did not get any respond
Looks like we failed to start activity.
/data/data/com.termux/files/usr/bin/linux-deploy: line 34: kill: (18038) - No such process
chmod: cannot access '/data/data/com.termux/files/usr/xwayland/wayland-0': No such file or directory

All preparations completed, connecting now

The authenticity of host 'localhost (127.0.0.1)' can't be established.
ED25519 key fingerprint is SHA256:kiv1jFMf3i1DBxhpvzswL6Uq4flGlKN18y1e699WhDI.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
android@localhost's password:
Linux localhost 4.19.270-NoGravityKernel-v1.2.0 #203 SMP PREEMPT Sun Jan 22 18:05:34 EST 2023 aarch64
Debian GNU/Linux 11 (bullseye) [running via

**Comment by klark231** [comment]
~ $ linux-deploy start -w

Initializing audio server before startup

Starting the chroot
Checking file system ... skip
Mounting the container:
/ ... skip
/proc ... skip
/sys ... skip
/dev ... skip
/dev/shm ... skip
/dev/pts ... skip
:: Configuring core/mnt ...
:: Configuring core/net ...
:: Starting extra/ssh ... skip

Binding internal storage

Binding external storage

Usage: bindfs [options] dir mountpoint
Information:
  -h      --help            Print this and exit.
  -V      --version         Print version number and exit.
          --fuse-version    Print version of FUSE library.

File ownership:
  -u      --force-user=...  Set file owner.
  -g      --force-group=... Set file group.
  -m      --mirror=...      Comma-separated list of users who will see
                            themselves as the owners of all files.
  -M      --mirror-only=... Like --mirror but disallow access for
                            all other users.
 --map=user1/user2:...      Let user2 see files of user1 as his own.
 --map-passwd=...           Load uid mapping from passwd-like file.
 --map-group=...            Load gid mapping from group-like file.
 --map-passwd-rev=...       Load reversed uid mapping from  passwd-like file.
 --map-group-rev=...        Load reversed gid mapping from group-like file.
 --uid-offset=...           Set file uid = uid + offset.
 --gid-offset=...           Set file gid = gid + offset.

Permission bits:
  -p      --perms=...       Specify permissions, similar to chmod
                            e.g. og-x,og+rD,u=rwX,g+rw  or  0644,a+X

File creation policy:
  --create-as-user          New files owned by creator (default for root). *
  --create-as-mounter       New files owned by fs mounter (default for users).
  --create-for-user=...     New files owned by specified user. *
  --create-for-group=...    New files owned by specified group. *
  --create-with-perms=...   Alter permissions of new files.

Chown policy:
  --chown-normal            Try to chown the original files (the default).
  --chown-ignore            Have all chowns fail silently.
  --chown-deny              Have all chowns fail with 'permission denied'.

Chgrp policy:
  --chgrp-normal            Try to chgrp the original files (the default).
  --chgrp-ignore            Have all chgrps fail silently.
  --chgrp-deny              Have all chgrps fail with 'permission denied'.

Chmod policy:
  --chmod-normal            Try to chmod the original files (the default).
  --chmod-ignore            Have all chmods fail silently.
  --chmod-deny              Have all chmods fail with 'permission denied'.
  --chmod-filter=...        Change permissions of chmod requests.
  --chmod-allow-x           Allow changing file execute bits in any case.

Extended attribute policy:
  --xattr-none              Do not implement xattr operations.
  --xattr-ro                Read-only xattr operations.
  --xattr-rw                Read-write xattr operations (the default).

Other file operations:
  --delete-deny             Disallow deleting files.
  --rename-deny             Disallow renaming files (within the mount).

Rate limits:
  --read-rate=...           Limit to bytes/sec that can be read.
  --write-rate=...          Limit to bytes/sec that can be written.

Miscellaneous:
  --no-allow-other          Do not add -o allow_other to fuse options.
  --realistic-permissions   Hide permission bits for actions mounter can't do.
  --ctime-from-mtime        Read file properties' change time
                            from file content modification time.
  --enable-lock-forwarding  Forward locks to the underlying FS.
  --enable-ioctl            Forward ioctl() calls (as the mounter).
  --hide-hard-links         Always report a hard link count of 1.
  --resolve-symlinks        Resolve symbolic links.
  --resolved-symlink-deletion=...  Decide how to delete resolved symlinks.
  --block-devices-as-files  Show block devices as regular files.
  --multithreaded           Enable multithreaded mode. See man page
                            for security issue with current implementation.
  --forward-odirect=...     Forward O_DIRECT (it's cleared by default).

FUSE options:
  -o opt[,opt,...]          Mount options.
  -r      -o ro             Mount strictly read-only.
  -d      -o debug          Enable debug output (implies -f).
  -f                        Foreground operation.

(*: root only)

Binfmt support not detected, skipping loading of binfmt entries
Creating the socket
:: Configuring core/mnt ...
:: Configuring core/net ...
Debian GNU/Linux 11 (bullseye) [running via Linux Deploy]
Starting: Intent { cmp=com.termux.x11/.MainActivity }
Loading shared library: /data/data/com.termux/files/usr/libexec/termux-x11/starter.apk!/lib/arm64-v8a/libx11-starter.so
res = 0
Activity is started
Got getWaylandFD
socket: Permission denied
Lorie requested fd
Got getLogFD
{ParcelFileDescriptor: java.io.FileDescriptor@ef6a2b9}
Got finish request
App sent finishing command
chmod: cannot access '/data/data/com.termux/files/usr/xwayland/wayland-0': No such file or directory

All preparations completed, connecting now

android@localhost's password:
Linux localhost 4.19.270-NoGravityKernel-v1.2.0 #203 SMP PREEMPT Sun Jan 22 18:05:34 EST 2023 aarch64
Debian GNU/Linux 11 (bullseye) [running via Linux Deploy]
Last login: Tue Jan 31 08:19:39 2023 from 127.0.0.1

**Comment by Pipetto-crypto** [comment]
>Usage: bindfs [options] dir mountpoint
Information:
-h --help Print this and exit.
-V --version Print version number and exit.
--fuse-version Print version of FUSE library.

>File ownership:
-u --force-user=... Set file owner.
-g --force-group=... Set file group.
-m --mirror=... Comma-separated list of users who will see
themselves as the owners of all files.
-M --mirror-only=... Like --mirror but disallow access for
all other users.
--map=user1/user2:... Let user2 see files of user1 as his own.
--map-passwd=... Load uid mapping from passwd-like file.
--map-group=... Load gid mapping from group-like file.
--map-passwd-rev=... Load reversed uid mapping from passwd-like file.
--map-group-rev=... Load reversed gid mapping from group-like file.
--uid-offset=... Set file uid = uid + offset.
--gid-offset=... Set file gid = gid + offset.

>Permission bits:
-p --perms=... Specify permissions, similar to chmod
e.g. og-x,og+rD,u=rwX,g+rw or 0644,a+X

>File creation policy:
--create-as-user New files owned by creator (default for root). *
--create-as-mounter New files owned by fs mounter (default for users).
--create-for-user=... New files owned by specified user. *
--create-for-group=... New files owned by specified group. *
--create-with-perms=... Alter permissions of new files.

>Chown policy:
--chown-normal Try to chown the original files (the default).
--chown-ignore Have all chowns fail silently.
--chown-deny Have all chowns fail with 'permission denied'.

>Chgrp policy:
--chgrp-normal Try to chgrp the original files (the default).
--chgrp-ignore Have all chgrps fail silently.
--chgrp-deny Have all chgrps fail with 'permission denied'.

>Chmod policy:
--chmod-normal Try to chmod the original files (the default).
--chmod-ignore Have all chmods fail silently.
--chmod-deny Have all chmods fail with 'permission denied'.
--chmod-filter=... Change permissions of chmod requests.
--chmod-allow-x Allow changing file execute bits in any case.

>Extended attribute policy:
--xattr-none Do not implement xattr operations.
--xattr-ro Read-only xattr operations.
--xattr-rw Read-write xattr operations (the default).

>Other file operations:
--delete-deny Disallow deleting files.
--rename-deny Disallow renaming files (within the mount).

>Rate limits:
--read-rate=... Limit to bytes/sec that can be read.
--write-rate=... Limit to bytes/sec that can be written.

>Miscellaneous:
--no-allow-other Do not add -o allow_other to fuse options.
--realistic-permissions Hide permission bits for actions mounter can't do.
--ctime-from-mtime Read file properties' change time
from file content modification time.
--enable-lock-forwarding Forward locks to the underlying FS.
--enable-ioctl Forward ioctl() calls (as the mounter).
--hide-hard-links Always report a hard link count of 1.
--resolve-symlinks Resolve symbolic links.
--resolved-symlink-deletion=... Decide how to delete resolved symlinks.
--block-devices-as-files Show block devices as regular files.
--multithreaded Enable multithreaded mode. See man page
for security issue with current implementation.
--forward-odirect=... Forward O_DIRECT (it's cleared by default).

>FUSE options:
-o opt[,opt,...] Mount options.
-r -o ro Mount strictly read-only.
-d -o debug Enable debug output (implies -f).
-f Foreground operation.


This is not a problem, you much likely don't have a SD Card slot so it is not capable to mount.

>Looks like we failed to start activity.

You may have to grant the app permissions inside your phone's settings. Also you need to stay in the app until you see the "Service was created" toast appears

>App sent finishing command

This is an issue on how the script kills the app. termux-x11 doesn't have a proper way of killing the app normally. If you want to avoid this happening you will have to kill the app manually from its notification before stopping and restarting the container

**Comment by klark231** [comment]
same thing. all permissions are allowed. already tried to restart

**Comment by Pipetto-crypto** [comment]
>same thing. all permissions are allowed. already tried to restart

does it work if you do it normally in termux?

Like open a termux tab and paste the command:

termux-x11

**Comment by klark231** [comment]
![Uploading Screenshot_2023-01-31-14-53-32-704_com.termux.jpg…]()

**Comment by klark231** [comment]
![Screenshot_2023-01-31-14-53-32-704_com termux](https://user-images.githubusercontent.com/11367357/215690561-735e50b5-7227-41ac-9442-dd86206237cd.jpg)

it wouldnt work

**Comment by Pipetto-crypto** [comment]
> ![Screenshot_2023-01-31-14-53-32-704_com termux](https://user-images.githubusercontent.com/11367357/215690561-735e50b5-7227-41ac-9442-dd86206237cd.jpg)
> 
> it wouldnt work

Try this, always inside termux:

pkg update && pkg upgrade
pkg install termux-x11

**Comment by klark231** [comment]
![Uploading Screenshot_2023-02-01-09-45-19-329_com.discord.jpg…]()

**Comment by klark231** [comment]
![Screenshot_2023-02-01-09-45-19-329_com discord](https://user-images.githubusercontent.com/11367357/215924784-a63cdf31-f8f0-40fc-a825-4cc1905cea7e.jpg)

**Comment by Pipetto-crypto** [comment]
That's not the issue here. If you are using my debian rootfs, then it has the right Wayland version also my script set everything automatically for you, so you don't need to do export anything.

If those instructions I gave you didn't work, you can try to reinstall termux-x11:

Delete the app, grab the termux-x11.zip either from this repo or from termux-x11 github page and extract it. Reinstall the apk, reinstall the deb and retry with the command "termux-x11" in termux and see if it works this time.

EDIT: Also those instructions you found there are mine, I gave them to someone on termux discord in January

**Comment by klark231** [comment]
> 

already tried this one. i guess you should ask one of your friend to try it. maybe youre using a very old version of android.  so you can verify it on your side. i tried it on two Android 12 devices and didnt work

**Comment by Pipetto-crypto** [comment]
> > 
> 
> already tried this one. i guess you should ask one of your friend to try it. maybe youre using a very old version of android. so you can verify it on your side. i tried it on two Android 12 devices and didnt work

termux-x11 should work on Android 12. I have a phone with A12 as well and it works without issues. You can try to open an issue on termux-x11 github since your issue seems to be specifically related to the termux-x11 app itself

**Comment by klark231** [comment]
> > > 
> > 
> > 
> > already tried this one. i guess you should ask one of your friend to try it. maybe youre using a very old version of android. so you can verify it on your side. i tried it on two Android 12 devices and didnt work
> 
> termux-x11 should work on Android 12. I have a phone with A12 as well and it works without issues. You can try to open an issue on termux-x11 github since your issue seems to be specifically related to the termux-x11 app itself

it works on proot. already tried wormtest tutorial

**Comment by Pipetto-crypto** [comment]
> it works on proot. already tried wormtest tutorial

What's the error you get in the chroot now, still the same as before like that?

> Android reported activity started but we did not get any respond
Looks like we failed to start activity.

This one?

EDIT: Before you retry, get the new updated linux-deploy script from this repo

**Comment by klark231** [comment]
> > it works on proot. already tried wormtest tutorial
> 
> What's the error you get in the chroot now, still the same as before like that?
> 
> > Android reported activity started but we did not get any respond
> > Looks like we failed to start activity.
> 
> This one?
> 
> EDIT: Before you retry, get the new updated linux-deploy script from this repo

i gave up with your script. i install from another guide. now my only problem is winetricks. youre guide is quite confusing

WINETRICKS

Move the executable you find here into /use/bin and give it executable permission:

sudo mv pathtowinetricks/winetricks /usr/bin

sudo chmod +x /usr/bin/winetricks

When you want to execute winetricks, run the following command 'win32 box64 winetricks

why is it win32? i tried running winetricks with BOX86_NOBANNER=1 winetricks and wont work

**Comment by Pipetto-crypto** [comment]
> why is it win32? i tried running winetricks with BOX86_NOBANNER=1 winetricks and wont work

Because win32 is the 32 bit prefix, Also winetricks is a x86 app so you need eithet box86 or 64 to run It

win32 box86 winetricks.

**Comment by wdlq** [comment]
> another guide

Can you please show me "the another guide"?  I use Android 11 and I failed.

**Comment by wdlq** [comment]
> > > it works on proot. already tried wormtest tutorial
> > 
> > 
> > What's the error you get in the chroot now, still the same as before like that?
> > > Android reported activity started but we did not get any respond
> > > Looks like we failed to start activity.
> > 
> > 
> > This one?
> > EDIT: Before you retry, get the new updated linux-deploy script from this repo
> 
> i gave up with your script. i install from another guide. now my only problem is winetricks. youre guide is quite confusing
> 
> WINETRICKS
> 
> Move the executable you find here into /use/bin and give it executable permission:
> 
> sudo mv pathtowinetricks/winetricks /usr/bin
> 
> sudo chmod +x /usr/bin/winetricks
> 
> When you want to execute winetricks, run the following command 'win32 box64 winetricks
> 
> why is it win32? i tried running winetricks with BOX86_NOBANNER=1 winetricks and wont work

Can you please show me "another guide"? I use Android 11 and I failed by this guide.

**Comment by wdlq** [comment]
@Pipetto-crypto 
env: exec   *******  No such file or directory
this is my termux console:

Success
I detected you are running Android 11 or newer which makes this script unlikely to work because of scoped storage restrictions. Attempting to fix, can't guarantee it will work

Copying config
mv: cannot move 'linux.conf' to '/data/user/0/ru.meefik.linuxdeploy/files/config': No such file or directory

Installing Termux-X11
Archive:  termux-x11.zip
  inflating: app-debug.apk
  inflating: output-metadata.json
  inflating: termux-x11.deb
dpkg: warning: downgrading termux-x11 from 1.02.07 to 1.02.06
(Reading database ... 14578 files and directories currently installed.)
Preparing to unpack termux-x11.deb ...
Unpacking termux-x11 (1.02.06) over (1.02.07) ...
Setting up termux-x11 (1.02.06) ...
Success

Starting installation
env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory

 Mounting container
env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory

 Copying installation scripts and required files to the chroot
chmod: cannot access '/data/local/mnt/home/u0_a213/scripts/*': No such file or directory

 Installing required dependencies
env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory
env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory

 Appending important env variables to profile and setting bash as the main shell
env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory

 Installing vnc and icewm
env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory

 Installing box64 and box86
env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory

 First setup completed, stopping the chroot
env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory

 Copying the linux-deploy wrapper script
~/Chroot-Docs $

**Comment by Pipetto-crypto** [comment]
> @Pipetto-crypto env: exec ******* No such file or directory this is my termux console:
> 
> Success I detected you are running Android 11 or newer which makes this script unlikely to work because of scoped storage restrictions. Attempting to fix, can't guarantee it will work
> 
> Copying config mv: cannot move 'linux.conf' to '/data/user/0/ru.meefik.linuxdeploy/files/config': No such file or directory
> 
> Installing Termux-X11 Archive: termux-x11.zip inflating: app-debug.apk inflating: output-metadata.json inflating: termux-x11.deb dpkg: warning: downgrading termux-x11 from 1.02.07 to 1.02.06 (Reading database ... 14578 files and directories currently installed.) Preparing to unpack termux-x11.deb ... Unpacking termux-x11 (1.02.06) over (1.02.07) ... Setting up termux-x11 (1.02.06) ... Success
> 
> Starting installation env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory
> 
> Mounting container env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory
> 
> Copying installation scripts and required files to the chroot chmod: cannot access '/data/local/mnt/home/u0_a213/scripts/*': No such file or directory
> 
> Installing required dependencies env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory
> 
> Appending important env variables to profile and setting bash as the main shell env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory
> 
> Installing vnc and icewm env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory
> 
> Installing box64 and box86 env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory
> 
> First setup completed, stopping the chroot env: exec /data/user/0/ru.meefik.linuxdeploy/files/bin/linuxdeploy: No such file or directory
> 
> Copying the linux-deploy wrapper script ~/Chroot-Docs $

https://github.com/meefik/linuxdeploy/issues/1346

You can try the fix suggested here else you can wait, I am working on a new script independent from LinuxDeploy. It has been tested and it is fully working even on Android 13 but there are some issues that need to be fixed before release.

**Comment by wdlq** [comment]
@Pipetto-crypto  Thank you!  I am looking forward to your new script.
